# Generated by Django 6.0.6 on 2026-07-03 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0002_order_branch_alter_order_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transaction', to='sales.order'),
        ),
    ]
