# Generated by Django 6.0.6 on 2026-09-28 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='The business owner: the only user who sees billing.'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed 4-6 digit PIN for cashier login.', max_length=128, null=True, validators=[django.core.validators.RegexValidator('^\\d{4,6}$', 'Pin must be 4  to 6 digits')]),
        ),
    ]
