# Generated by Django 6.0.6 on 2026-10-02 05:55

import backups.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Automatic')], max_length=10)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('file', models.FileField(blank=True, max_length=255, storage=backups.models.backup_storage, upload_to='')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 of the stored file', max_length=64)),
                ('encrypted', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10)),
                ('hour', models.PositiveSmallIntegerField(default=2, help_text='Run after this hour (0-23, local time).')),
                ('keep_last', models.PositiveSmallIntegerField(default=14, help_text='Automatic backups to keep.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_backup_schedule_per_tenant')],
            },
        ),
    ]
