# Generated by Django 6.0.6 on 2026-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_changed',
            field=models.DecimalField(decimal_places=3, help_text='Can be negative (for damage/loss) or positive (for corrections).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
