# Generated by Django 6.0.6 on 2026-07-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchaseorderitem_quantity_ordered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'ordering': ['-branch']},
        ),
    ]
