# Generated by Django 6.0.6 on 2026-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stocklevel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('COUNT', 'Stock Count / Audit'), ('DAMAGE', 'Damaged Items Written Off'), ('THEFT', 'Stolen / Missing'), ('EXPIRY', 'Expired Items'), ('CORRECTION', 'Data Entry Correction')], max_length=20),
        ),
    ]
