# Generated by Django 6.0.6 on 2026-09-28 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_adjustment_type'),
        ('sales', '0011_alter_cashregistersession_branch'),
        ('supplier', '0004_alter_supplier_options_remove_supplier_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional — leave blank for market/individual/other informal purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='supplier.supplier'),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MPESA', 'M-Pesa')], max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Bank/M-Pesa transaction code or receipt number, if applicable.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_transaction', models.OneToOneField(blank=True, help_text='The branch cash-pool withdrawal this payment created, if paid in cash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payment', to='sales.cashtransaction')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
