# Generated by Django 6.0.6 on 2026-09-28 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_branch_tenant_inventorytransfer_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.branch'),
        ),
    ]
