# Generated by Django 6.0.6 on 2026-10-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorytransfer_to_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('OPENING', 'Opening Stock (Initial Setup)'), ('COUNT', 'Stock Count / Audit'), ('DAMAGE', 'Damaged Items Written Off'), ('THEFT', 'Stolen / Missing'), ('EXPIRY', 'Expired Items'), ('CORRECTION', 'Data Entry Correction')], max_length=20),
        ),
    ]
