# Generated by Django 6.0.6 on 2026-10-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockadjustment_adjustment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
    ]
