"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY  = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# CHANGED FOR PWA/PRODUCTION HARDENING: this was hardcoded to True.
# It now defaults to True for local/ngrok dev (unchanged behaviour if
# you don't set anything), but MUST be set to False via the DEBUG env
# var in production — the HTTPS/security block below only activates
# when DEBUG is False, and a service worker will refuse to register
# on a plain-HTTP production origin anyway (see notes below).
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = [
    '127.0.0.1',
    '.ngrok-free.app'
]

if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app'
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'payments',
    'products',
    'supplier',
    'sales',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ADDED FOR PWA: project-level templates dir so templates/pwa/
        # (service-worker.js, offline.html) are found. Your existing
        # per-app templates (e.g. users/templates/users/...) still work
        # unchanged via APP_DIRS below.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ADDED FOR PWA: tells collectstatic where to find the project-level
# static/ folder (manifest.json, static/icons/*.png). If you already
# have your own STATICFILES_DIRS elsewhere, merge BASE_DIR / 'static'
# into it instead of duplicating this setting.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/users/pos-login/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/users/pos-login/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'users.backends.PINAuthenticationBackend',
]


MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MPESA_ENVIRONMENT=env('DARAJA_ENVIRONMENT', default='sandbox')
MPESA_CONSUMER_KEY=env('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET=env('MPESA_CONSUMER_SECRET')
MPESA_SHORTCODE=env('MPESA_SHORTCODE')
MPESA_PASSKEY=env('MPESA_PASSKEY')
MPESA_CALLBACK_URL=env('MPESA_CALLBACK_URL')


# --- PWA / production HTTPS hardening ---------------------------------
# ADDED FOR PWA. A service worker (required for installability, the
# manifest to be honoured, and offline support) only registers on
# "secure contexts": https://, or http://localhost / http://127.0.0.1.
# This block only takes effect when DEBUG is False, so local dev
# (DEBUG=True, plain http://127.0.0.1) and your existing ngrok flow
# (already https://) are unaffected either way.
if not DEBUG:
    # Render (and most PaaS hosts) terminate TLS at a proxy and forward
    # plain HTTP internally, so Django needs this header to know the
    # original request was HTTPS — without it, SECURE_SSL_REDIRECT
    # below would redirect-loop forever.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week to start; raise once confirmed stable
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'