# Generated by Django 6.0.6 on 2026-06-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
        ('supplier', '0002_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, help_text='The SKU code this specific supplier uses.', max_length=100)),
                ('lead_time_days', models.PositiveBigIntegerField(default=7, help_text='Average days it takes this supplier to deliver this item.')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this our preferred vendor for this product?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='supplier.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Product Link',
                'ordering': ['is_primary', 'product__name'],
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
