# Generated by Django 6.0.6 on 2026-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplierproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
