# Generated by Django 6.0.6 on 2026-09-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_options_remove_supplier_company_name_and_more'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
