# Generated by Django 6.0.6 on 2026-09-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_cashregistersession_order_cash_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregistersession',
            name='expected_closing_balance',
        ),
    ]
