# Generated by Django 6.0.6 on 2026-09-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_cashregistersession_expected_closing_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregistersession',
            name='expected_closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
