# Generated by Django 6.0.6 on 2026-09-25 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_adjustment_type'),
        ('sales', '0005_cashregistersession_expected_closing_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregistersession',
            name='cashier',
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash physically handed over by the customer', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Change handed back to the customer (amount_received - total_revenue)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_IN', 'Cash In (Float Addition)'), ('CASH_OUT', 'Cash Out (Withdrawal)')], default='CASH_IN', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash')], default='CASH', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('branch',), name='one_open_cash_session_per_branch'),
        ),
    ]
