# Generated by Django 6.0.6 on 2026-09-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_cashregistersession_cashier_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashregistersession',
            name='one_open_cash_session_per_branch',
        ),
    ]
