# Generated by Django 6.0.6 on 2026-09-25 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_adjustment_type'),
        ('sales', '0007_remove_cashregistersession_one_open_cash_session_per_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('branch',), name='one_open_cash_session_per_branch'),
        ),
    ]
