# Generated by Django 6.0.6 on 2026-09-25 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_adjustment_type'),
        ('sales', '0009_alter_cashregistersession_opened_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregistersession',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='inventory.branch'),
            preserve_default=False,
        ),
    ]
