# Generated by Django 6.0.6 on 2026-09-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_adjustment_type'),
        ('sales', '0010_alter_cashregistersession_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregistersession',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='inventory.branch'),
        ),
    ]
