# Generated by Django 6.0.6 on 2026-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=12),
        ),
    ]
