# Generated by Django 6.0.6 on 2026-09-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_low_stock_threshold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
