# Generated by Django 6.0.6 on 2026-09-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_productimage'),
        ('supplier', '0004_alter_supplier_options_remove_supplier_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supplier.supplier'),
        ),
    ]
