# Generated by Django 6.0.6 on 2026-10-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_tenant_category_tenant_product_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_variant',
            field=models.ForeignKey(blank=True, help_text='Set only for packs; points at the unit that holds the stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packagings', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit_name',
            field=models.CharField(blank=True, help_text="How it's sold: Tablet, Packet, Box", max_length=30),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='units_per_pack',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
